# Generated by Django 5.2.7 on 2025-10-26 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aob', '0002_table_row_column_cell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cell_columns', to='aob.column'),
        ),
    ]
